### PR TITLE
feat(volar): support defineSlots for vue2

### LINKED ISSUE #524: jsxDirective `v-slot` and `defineSlots` in Vue 2 are incompatible
### Describe the bug

See the commit 4c8d8ea8c5edd83fc2f6ec04c3279a4515a8aa23

---

- Volar now support typed slots in Vue 2, but it doesn't work with Vue Macros in Vue 2.
- The docs shows that JSX Directive `v-slot` supports Vue 2, but there are errors in playground/vue2

### Reproduction

N/A

### System Info

```Shell
N/A
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by zhiyuanzmj**
### Description

closed #524

### CODE REVIEW

**Comment by zhiyuanzmj** [comment]
Wait for volar v1.8.20, the ts-error with defineSlots in vue2 will be fixed.
https://github.com/vuejs/language-tools/pull/3669#event-10657270992

**Comment by sxzz** [comment]
@zhiyuanzmj v1.8.20 is released & upgraded in Vue Macros.

**Comment by zhiyuanzmj** [comment]
Ok, TBR.

**Review by sxzz — APPROVED** [review]
LGTM

**Pull request merged**
