### PR TITLE
feat(docs): improve style of Interactive Example

### PR DESCRIPTION
**Pull request by isolcat**
### Description
I felt that the previous Interactive Example was a bit skimpy, so I thought I'd add a bit of style to it,the style references the VueUse.
Modify the style of Interactive Example,The modified style is as follows:

### CODE REVIEW

**Review by sxzz — COMMENTED** [review]
The text color is not suitable for dark mode
image

**Comment by isolcat** [comment]
> The text color is not suitable for dark mode image
I'm sorry I didn't take that into account, let me try another color!

**Comment by isolcat** [comment]
Maybe this would be better now?

**Comment by sxzz** [comment]
I think the white text is more clear in light mode
image

**Comment by isolcat** [comment]
I think so, this look seems to be more in line with the theme of Vue Macros

**Comment by sxzz** [comment]
Merged. Thanks for your contribution!

**Pull request merged**
